In [72]:
import numpy as np

A = ([[0],[1],[2],[3],[4],[5]])
B = ([[0,1,2,3,4,5,6,7]])
matrix = np.dot(A,B)
print(matrix)
print(matrix.max())

[[ 0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7]
 [ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]
 [ 0  4  8 12 16 20 24 28]
 [ 0  5 10 15 20 25 30 35]]
35
